[package]
name = "sl-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
regex.workspace = true
rhai.workspace = true
sl-core = { path = "../sl-core" }

[dev-dependencies]
sl-compiler = { path = "../sl-compiler" }
