[package]
name = "sl-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
regex.workspace = true
serde_json.workspace = true
sl-core = { path = "../sl-core" }
sl-parser = { path = "../sl-parser" }
