[package]
name = "sl-api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sl-core = { path = "../sl-core" }
sl-compiler = { path = "../sl-compiler" }
sl-runtime = { path = "../sl-runtime" }
